<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-ERPL0N8" failures="1" tests="3" name="TestNg Secuencial runner Tests" time="238.073" errors="0" timestamp="12 mar. 2022 00:52:07 GMT">
  <testcase classname="cucumber.api.testng.AbstractTestNGCucumberTests" name="runScenario" time="70.431"/>
  <testcase classname="cucumber.api.testng.AbstractTestNGCucumberTests" name="runScenario" time="67.946"/>
  <testcase classname="cucumber.api.testng.AbstractTestNGCucumberTests" name="runScenario" time="92.823">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at lippia.web.services.AutomationService.verifyResults(AutomationService.java:67)
at lippia.web.steps.AutomationWebSteps.theClientVerifyThatResultsAreShownProperly(AutomationWebSteps.java:43)
at âœ½.The client verify that results are shown properly.(file:src/test/resources/web/features/AutomationPractice.feature:23)
... Removed 4 stack frames]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- TestNg Secuencial runner Tests -->
