<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-ERPL0N8" failures="1" tests="3" name="TestNg Secuencial runner Tests" time="73.973" errors="0" timestamp="09 feb. 2022 15:53:16 GMT">
  <testcase classname="cucumber.api.testng.AbstractTestNGCucumberTests" name="runScenario" time="36.812"/>
  <testcase classname="cucumber.api.testng.AbstractTestNGCucumberTests" name="runScenario" time="18.229"/>
  <testcase classname="cucumber.api.testng.AbstractTestNGCucumberTests" name="runScenario" time="16.713">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at lippia.web.services.AutomationHomeService.verifyResults(AutomationHomeService.java:65)
at lippia.web.steps.AutomationWebSteps.theClientVerifyThatResultsAreShownProperly(AutomationWebSteps.java:63)
at âœ½.The client verify that results are shown properly.(file:src/test/resources/web/features/AutomationPractice.feature:23)
... Removed 4 stack frames]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- TestNg Secuencial runner Tests -->
